#!/usr/bin/env python3
"""Build static engineering pages from engineering-copy.json; --check rejects stale output."""
from site_header import apply as apply_header
import argparse
import json
from html import escape as e
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COPY = json.loads((ROOT / 'scripts/engineering-copy.json').read_text())

def render(c, lang):
    example = c['examples'][0]
    choices = '\n'.join(f'<button type="button" data-example="{i}" aria-pressed="{str(i == 0).lower()}" aria-controls="example-result">{e(item["label"])}</button>' for i,item in enumerate(c['examples']))
    outputs = '\n'.join(f'<li><span class="check" aria-hidden="true">✓</span><span data-output="{i}">{e(text)}</span></li>' for i,text in enumerate(example['outputs']))
    def flow(items):
        return ''.join(f'<li>{e(item)}</li>' for item in items)
    setup = '\n'.join(f'<li><span class="setup-number">{i+1}</span><div><h3>{e(title)}</h3><p>{e(body)}</p></div></li>' for i,(title,body) in enumerate(c['setup']))
    levels = '\n'.join(f'''<details class="level" name="assurance"{' open' if i == 2 else ''}>
      <summary><span class="level-number">{l[0]}</span><strong>{e(l[1])}{f'<small>{e(c["default"])}</small>' if i == 2 else ''}</strong><span class="level-use">{e(l[2])}</span><span class="toggle" aria-hidden="true">+</span></summary>
      <div class="level-detail"><p>{e(l[3])}</p><p>{e(l[4])}</p></div>
    </details>''' for i,l in enumerate(c['levels']))
    prefix = '/guides/' if lang == 'ja' else '/guides/en/'
    related = ''.join(f'<li><a href="{prefix}{slug}.html">{label}</a></li>' for slug,label in [
        ('simy-getting-started', 'SIMYの始め方' if lang == 'ja' else 'Getting started with SIMY'),
        ('simy-delivery-loop', 'Delivery Loopの使い方' if lang == 'ja' else 'Using Delivery Loop'),
        ('simy-sqm', 'SQMの使い方' if lang == 'ja' else 'Using SQM'),
        ('claude-code', 'Claude Code'), ('conductor', 'Conductor')])
    data = json.dumps(c['examples'],ensure_ascii=False).replace('<','\\u003c')
    headline = ''.join(f'<span>{e(line)}</span>' for line in c['headline'])
    schema = json.dumps({"@context": "https://schema.org", "@type": "WebPage", "name": c['title'], "description": c['description'], "url": 'https://simy.one/' + c['path'], "inLanguage": lang, "isPartOf": {"@type": "WebSite", "name": "SIMY", "url": "https://simy.one/"}}, ensure_ascii=False).replace('<', '\\u003c')
    return f'''<!doctype html>
<!-- Generated by scripts/build-engineering-pages.py; edit scripts/engineering-copy.json. -->
<html lang="{lang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{e(c['title'])}</title>
  <meta name="description" content="{e(c['description'])}">
  <link rel="canonical" href="https://simy.one/{c['path']}">
  <link rel="alternate" hreflang="ja" href="https://simy.one/for/engineers/">
  <link rel="alternate" hreflang="en" href="https://simy.one/for/en/engineers/">
  <link rel="alternate" hreflang="x-default" href="https://simy.one/for/en/engineers/">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{e(c['title'])}">
  <meta property="og:description" content="{e(c['description'])}">
  <meta property="og:url" content="https://simy.one/{c['path']}">
  <meta property="og:image" content="https://simy.one/ogp-home-global-202608-v4.png">
  <meta name="robots" content="index, follow">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{e(c['title'])}">
  <meta name="twitter:description" content="{e(c['description'])}">
  <meta name="twitter:image" content="https://simy.one/ogp-home-global-202608-v4.png">
  <script type="application/ld+json">{schema}</script>
  <meta name="theme-color" content="#f6f5f4">
  <link rel="icon" href="/favicon-32.png" type="image/png">
  <link rel="stylesheet" href="/site-theme.css?v=20261004-theme-1">
  <link rel="stylesheet" href="/engineers.css?v=20261004-theme-1">
  <script src="/engineers.js?v=20261003-clarity-2" defer></script>
</head>
<body>
<a class="skip" href="#main">{c['skip']}</a>
<header class="header">
  <div class="site-shell"><div class="frame header-inner">
    <a class="brand" href="{c['home']}" aria-label="SIMY"><img src="/favicon.png" width="32" height="32" alt=""><b>SIMY</b></a>
    <nav aria-label="{'ナビゲーション' if lang == 'ja' else 'Navigation'}"><a href="#delivery">{c['nav']}</a><a href="#start">{c['start']}</a></nav>
    <div class="header-actions"><a class="language" href="/{c['other']}" lang="{'en' if lang == 'ja' else 'ja'}">{c['otherlabel']}</a><a class="button button-dark button-small header-download" href="{c['download']}">{"ダウンロード" if lang == "ja" else "Download"} <span aria-hidden="true">↗</span></a></div>
  </div></div>
</header>
<main id="main" class="site-shell">
  <section class="hero">
    <div class="frame">
      <div class="hero-copy">
        <p class="eyebrow">{c['eyebrow']}</p>
        <h1>{headline}</h1>
        <p class="hero-lead">{c['lead']}<br>{c['sublead']}</p>
        <div class="hero-actions"><a class="button button-primary primary" href="{c['download']}">{c['install']}<span aria-hidden="true">↗</span></a><a class="secondary" href="#example">{c['secondary']}<span aria-hidden="true">↓</span></a></div>
        <p class="provider">{c['provider']}</p>
      </div>
      <div class="example" id="example">
        <div class="example-top"><h2>{c['exampleLabel']}</h2><div class="example-choices" role="group" aria-label="{c['choicesLabel']}" data-enhancement hidden>{choices}</div></div>
        <div class="example-grid" id="example-result">
          <div class="request"><span class="label">{c['requestLabel']}</span><h3 data-request>{e(example['request'])}</h3><p data-hint>{e(example['hint'])}</p></div>
          <div class="result"><span class="result-arrow" aria-hidden="true">→</span><span class="label">{c['returnLabel']}</span><ul>{outputs}</ul></div>
        </div>
        <div class="example-bottom"><p data-benefit>{e(example['benefit'])}</p><span>{c['returnNote']}</span></div>
        <p class="sr-only" data-announcement aria-live="polite" aria-atomic="true"></p>
      </div>
      <p class="example-note">{c['exampleNote']}</p>
      <noscript><p class="example-note">{c['nojs']}</p></noscript>
    </div>
  </section>
  <section class="section frame" id="delivery">
    <h2 class="section-title">{c['howTitle']}</h2>
    <div class="capabilities">
      <article class="capability"><span class="product-name">DELIVERY LOOP</span><h3>{c['loopTitle']}</h3><p>{c['loopBody']}</p><ol class="flow">{flow(c['loopSteps'])}</ol><small>{c['loopFoot']}</small></article>
      <article class="capability" id="sqm"><span class="product-name">SQM / SOFTWARE QUALITY MONITOR</span><h3>{c['sqmTitle']}</h3><p>{c['sqmBody']}</p><ol class="flow">{flow(c['sqmSteps'])}</ol><small>{c['sqmFoot']}</small></article>
    </div>
  </section>
  <section class="faq-section frame" aria-labelledby="faq-title">
    <h2 id="faq-title">{c['detailsTitle']}</h2>
    <div class="faq-list">
      <details class="faq"><summary>{c['scopeQuestion']}<span class="toggle" aria-hidden="true">+</span></summary><div class="answer"><p>{c['scopeAnswer']}</p></div></details>
      <details class="faq"><summary>{c['controlQuestion']}<span class="toggle" aria-hidden="true">+</span></summary><div class="answer"><p>{c['controlAnswer']}</p></div></details>
      <details class="faq" id="levels"><summary>{c['levelQuestion']}<span class="toggle" aria-hidden="true">+</span></summary><div class="answer"><p>{c['levelIntro']}</p><div class="level-list">{levels}</div><p class="level-note">{c['levelNote']}</p></div></details>
    </div>
  </section>
  <section class="start-section" id="start"><div class="frame">
    <h2 class="section-title">{c['ctaTitle']}</h2>
    <ol class="setup">{setup}</ol>
    <div class="start-actions"><a class="button button-primary primary" href="{c['download']}">{c['install']} <span aria-hidden="true">↗</span></a><a class="secondary" href="{c['home']}#pricing">{c['pricing']} <span aria-hidden="true">→</span></a></div>
    <p class="availability">{c['availability']}</p>
  </div></section>
  <section class="section frame" aria-labelledby="related-title"><h2 id="related-title">{'具体的な手順を読む' if lang == 'ja' else 'Read the practical steps'}</h2><ul>{related}</ul><p><a href="{'/for/' if lang == 'ja' else '/for/en/'}">{'職業別の活用を見る' if lang == 'ja' else 'Explore SIMY for your work'}</a></p></section>
</main>
<footer class="site-shell"><div class="frame footer"><a class="brand" href="{c['home']}"><b>SIMY</b><span>{c['back']} ↗</span></a><p>{c['footerNote']}</p><span>© 2026 SIMY</span></div></footer>
<script type="application/json" id="engineering-data">{data}</script>
</body>
</html>'''

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    for lang,c in COPY.items():
        path = ROOT/'site'/c['path']/'index.html'
        output = apply_header(render(c,lang)+'\n', path)
        if args.check:
            if not path.exists() or path.read_text() != output:
                raise SystemExit(f'Stale engineering page: {path.name}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(output)
    for lang, legacy in [('ja', 'engineers.html'), ('en', 'engineers-en.html')]:
        url = '/' + COPY[lang]['path']
        label = 'エンジニア向けページを見る' if lang == 'ja' else 'View SIMY for engineers'
        alias = f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="robots" content="noindex, follow"><meta name="viewport" content="width=device-width, initial-scale=1"><title>SIMY — {label}</title><link rel="canonical" href="https://simy.one{url}"><meta http-equiv="refresh" content="0; url={url}"></head><body><a href="{url}">{label}</a></body></html>
'''
        path = ROOT/'site'/legacy
        if args.check:
            if not path.exists() or path.read_text() != alias:
                raise SystemExit(f'Stale engineering alias: {legacy}')
        else:
            path.write_text(alias)
    print('Engineering pages verified.'  if args.check else 'Engineering pages generated.')
