#!/usr/bin/env python3
"""Build all six localized FP experience pages; --check detects stale output."""
import argparse
import json
from pathlib import Path
from site_header import apply as apply_header
from financial_planner_risks import section as risk_section
from financial_planner_locale import LOCALES, route as locale_route, translator

ROOT = Path(__file__).resolve().parents[1]

def render(lang):
    t = translator(lang)
    def badge(ja, en, tone=''): return f'<span class="badge {tone}">{t(ja,en)}</span>'
    def pane(n, content): return f'<div data-panel="{n}">{content}</div>'
    def tabs(labels):
        return '<div class="screen-tabs" data-controls hidden role="group" aria-label="'+t('画面を切り替える','Choose a screen')+'">'+''.join(f'<button type="button" data-step="{i}" aria-pressed="{str(i==0).lower()}">{i+1:02d} {t(*label)}</button>' for i,label in enumerate(labels))+'</div>'
    def screen(content, title, kind=''):
        return f'<div class="app-screen {kind}"><div class="app-bar"><b><img src="/favicon-32.png" width="22" height="22" alt=""> SIMY</b><span>{title}</span>{badge("画面イメージ","Illustrative UI")}</div>{content}</div>'
    route = locale_route(lang)
    home = '/' if lang == 'en' else f'/{lang}.html'
    download = '/download.html' if lang == 'ja' else f'/download/{lang.lower()}.html'
    alternates = ''.join(f'<link rel="alternate" hreflang="{code}" href="https://simy.one{locale_route(code)}">' for code in LOCALES)
    title = t('SIMY for Financial Planners — 面談の前も、後も、次の一手へ。','SIMY for Financial Planners — Ready for the next conversation.')
    description = t('面談記録から確認事項とフォロー文面を下書き。iOSアプリで音声ロールプレイ。先輩の経験を次の面談に活かす、FPのためのSIMYを画面イメージで紹介。','Turn meeting notes into questions and follow-up drafts. Rehearse out loud in the iOS app and bring your team’s experience into your next client conversation.')
    sample = t('架空のお客さま・説明用の画面です。','Fictional client. Illustrative screens.')
    customer = t('佐藤さま｜初回相談','Sato family · First consultation')
    profile = t('第二子の誕生・住宅購入を検討中','Second child · Considering a new home')
    summary = f'''<p class="ui-kicker">{t('面談から整理したこと','FROM YOUR CONVERSATION')}</p><h3>{t('次回は、家計の全体像から。','Start with the household picture.')}</h3><div class="fact-list"><div>{badge('確認済み','Confirmed','green')}<p>{t('住宅購入と教育費を、一緒に考えたい。','Wants to plan for a home and education together.')}</p></div><div>{badge('仮説','Hypothesis')}<p>{t('毎月の固定費が増えることに、不安があるかもしれない。','May be concerned about rising monthly commitments.')}</p></div><div>{badge('次回確認','To confirm','amber')}<p>{t('住宅予算・購入時期・ご夫婦の優先順位。','Home budget, timing and each partner’s priorities.')}</p></div></div><div class="source-note">↳ {t('確認済みの根拠：面談メモ 12:40','Confirmed item source: meeting notes, 12:40')}</div>'''
    draft = f'''<p class="ui-kicker">{t('フォローメールの下書き','FOLLOW-UP DRAFT')}</p><h3>{t('次の面談につながる、一通。','A clear next step, in one message.')}</h3><div class="email-draft"><b>{t('本日のご相談のお礼と、次回の確認事項','Thank you — and a few questions for next time')}</b><p>{t('本日はありがとうございました。次回は、住宅購入のご希望と教育費について、ご家族の優先順位を一緒に整理できればと思います。','Thank you for meeting today. Next time, let’s explore your family’s priorities for buying a home and planning for education.')}</p><p>{t('購入時期や月々のご予算について、ご夫婦でお話しされたことがあればお聞かせください。','Please share any conversations you have had with your partner about timing and your monthly budget.')}</p></div><div class="review-line">{badge('未送信・要確認','Not sent · Review needed','amber')}<span>{t('担当FPが確認・修正してから送信','Your FP reviews and edits before sending')}</span></div>'''
    pack = f'''<p class="ui-kicker">{t('面談完了パック','MEETING FOLLOW-UP PACK')}</p><h3>{t('確認するものが、一か所に。','Everything to review, together.')}</h3><ul class="pack-list">'''+''.join(f'<li><span>✓</span>{t(*x)}<small>{t("下書き","Draft")}</small></li>' for x in [('現状・課題・意向の整理','Situation, concerns and preferences'),('確認済み・次回確認事項','Confirmed facts and open questions'),('FP設計ソフトの入力候補','Draft entries for planning software'),('比較に必要な情報','Information needed for comparison'),('次回アジェンダ・提案資料','Next agenda and presentation outline'),('お客さまへのフォロー文面','Client follow-up message')])+f'</ul><p class="source-note">{t("入力候補は差分を確認。保存・送信はご本人が判断します。","Review proposed entries. You decide what to save and send.")}</p>'
    desktop = screen(f'''<div class="desktop-layout"><aside class="app-sidebar"><span class="sidebar-label">{t("ワークスペース","WORKSPACE")}</span><span>{t('ホーム','Home')}</span><span>{t('お客さま','Clients')}</span><strong>{t('面談フォロー','Meeting follow-up')}</strong><span>{t('ナレッジ','Knowledge')}</span><div class="sidebar-bottom">{t("FPチーム","FP TEAM")}<br><small>{t('相談を、次の一歩へ。','Make each conversation count.')}</small></div></aside><div class="desktop-main"><div class="client-bar"><div><b>{customer}</b><small>{profile}</small></div>{badge('確認待ち','Ready for review','green')}</div><div data-demo="meeting">{tabs([('整理する','Organize'),('下書きを読む','Read draft'),('まとめて確認','Review pack')])}<div class="screen-content">{pane(0,summary)}{pane(1,draft)}{pane(2,pack)}</div></div></div></div>''',t('面談フォロー','Meeting follow-up'))
    hero = screen(f'''<div class="hero-screen-body"><div class="hero-client"><span class="avatar">S</span><div><b>{customer}</b><small>{profile}</small></div>{badge('要確認','Review','amber')}</div><p class="ui-kicker">{t('あなたへの引き継ぎ','READY FOR YOU')}</p><h2>{t('面談の続きは、<br>もう下書きに。','Your next steps.<br>Already drafted.')}</h2><div class="hero-deliverables"><div><span>01</span><b>{t('お客さまの意向','Client priorities')}</b><small>{t('事実と仮説を分けて整理','Facts separated from hypotheses')}</small></div><div><span>02</span><b>{t('次に聞きたいこと','What to ask next')}</b><small>{t('未確認の論点をピックアップ','Open questions brought together')}</small></div><div><span>03</span><b>{t('次回の準備とフォロー','Preparation and follow-up')}</b><small>{t('アジェンダ・連絡文面の下書き','Draft agenda and client message')}</small></div></div><div class="hero-handoff"><span class="check-circle">✓</span>{t('最後の確認と判断は、あなたに。','The final review and decision are yours.')}</div></div>''',t('面談完了パック','Meeting follow-up pack'),'hero-screen')
    phone_setup = f'''<div class="phone-heading"><span class="phone-symbol">◎</span><p class="ui-kicker">{t('今日の練習テーマ','TODAY’S PRACTICE')}</p><h3>{t('商品の前に、<br>想いを聞く。','Listen first.<br>Understand more.')}</h3><p>{profile}</p></div><div class="phone-card"><span class="badge green">{t('AIがお客さま役','AI plays the client')}</span><p>{t('「妻とは一緒に決めますが、まだ納得していません」','“My wife and I decide together, but she isn’t comfortable yet.”')}</p></div><p class="phone-note">{t('最初の質問を、声に出して練習。','Practice your opening question out loud.')}</p>'''
    phone_talk = f'''<div class="session-label"><span class="live-dot"></span>{t('音声ロールプレイ','Voice role-play')}<span>02:34</span></div><div class="speech client"><small>{t('AI・お客さま役','AI · Client')}</small><p>{t('妻とは一緒に決めますが、まだ納得していません。','My wife and I decide together, but she isn’t comfortable yet.')}</p></div><div class="speech advisor"><small>{t('あなた・FP','You · Financial planner')}</small><p>{t('奥さまは、どの点を気にされていますか？','What is your partner most concerned about?')}</p></div><div class="voice-orb" aria-hidden="true"><div class="wave">'''+''.join(f'<i style="--h:{v}px"></i>' for v in [12,22,34,48,30,56,40,24,42,28,16])+f'''</div></div><p class="phone-note">{t('お客さまの反応を聞きながら、会話を続ける。','Continue the conversation, listening to the client’s response.')}</p><div class="call-controls" aria-hidden="true"><span>Ⅱ</span><span class="mic-icon">◉</span><span>×</span></div>'''
    phone_review = f'''<div class="phone-heading compact"><span class="phone-symbol">✓</span><p class="ui-kicker">{t('練習の振り返り','PRACTICE REFLECTION')}</p><h3>{t('次は、もう一歩<br>深く聞ける。','Go one question<br>deeper next time.')}</h3></div><div class="phone-card"><b>{t('よかった問いかけ','A helpful question')}</b><p>{t('商品説明の前に、一緒に決めるご家族の懸念を聞けました。','You asked about the concerns of the partner who shares the decision before discussing products.')}</p></div><div class="phone-card next-question"><b>{t('次に試す質問','A question to try next')}</b><p>{t('「今の暮らしを保つために、毎月いくらを残したいですか？」','“How much would you like to keep available each month for your daily life?”')}</p></div><p class="phone-note">{t('ご家族の合意は、次回面談で要確認。','Check family agreement at the next meeting.')}</p>'''
    phone = f'''<div class="phone" aria-label="{t('iOSアプリの画面イメージ','Illustrative iOS app screen')}"><div class="ios-status"><b>9:41</b><span class="dynamic-island" aria-hidden="true"></span><span aria-hidden="true">▮▮▮ ▰</span></div><div class="phone-nav"><span aria-hidden="true">‹</span><b>SIMY</b><span>···</span></div><div class="phone-body">{pane(0,phone_setup)}{pane(1,phone_talk)}{pane(2,phone_review)}</div><div class="home-indicator" aria-hidden="true"></div></div>'''
    knowledge = screen(f'''<div class="knowledge-body"><div class="client-bar"><div><small>{t('明日 15:00 / 初回相談','TOMORROW, 15:00 / FIRST CONSULTATION')}</small><h3>{t('この面談に、先輩の経験を。','The right experience for this meeting.')}</h3></div></div><div class="knowledge-grid"><div><p class="ui-kicker">{t('似たケースの、質問の順番','QUESTIONS FROM A SIMILAR CASE')}</p><ol class="question-list"><li><b>{t('生活の変化から聞く','Start with changes in daily life')}</b><p>{t('お子さまが生まれて、一番変わったことは？','What changed most when your child was born?')}</p></li><li><b>{t('希望を具体的にする','Make the goals concrete')}</b><p>{t('住宅購入は、いつ頃を考えていますか？','When would you like to buy a home?')}</p></li><li><b>{t('一緒に決める人を確認','Understand who decides together')}</b><p>{t('ご夫婦で決まっていることはありますか？','What have you already agreed on as a couple?')}</p></li></ol></div><aside class="coaching-note"><span class="badge amber">{t('先輩が気づいた赤信号','A red flag a colleague noticed')}</span><h4>{t('提案を急がず、<br>優先順位をそろえる。','Align on priorities<br>before proposing.')}</h4><p>{t('月々の負担について合意が取れているか、次回の面談で確認しましょう。','Use the next meeting to check whether the couple agrees on an affordable monthly commitment.')}</p><small>{t('匿名化・共有承認済みの事例を活用','Use anonymized cases approved for sharing')}</small></aside></div></div>''',t('面談前の準備','Meeting preparation'))
    steps = [('面談の後に','After the meeting'),('営業の赤信号','Sales red flags'),('面談の前に','Before the meeting'),('チームの経験から','Learn from the team')]
    return f'''<!doctype html>
<!-- Generated by scripts/build-financial-planner-pages.py. -->
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><meta name="description" content="{description}"><link rel="canonical" href="https://simy.one{route}">
{alternates}<link rel="alternate" hreflang="x-default" href="https://simy.one/for/en/financial-planners/">
<meta name="robots" content="index, follow"><meta property="og:type" content="website"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="https://simy.one{route}"><meta property="og:image" content="https://simy.one/assets/fp-experience/social-{lang}.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{title}"><meta name="twitter:description" content="{description}"><meta name="twitter:image" content="https://simy.one/assets/fp-experience/social-{lang}.png">
<script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@type':'WebPage','name':title,'description':description,'url':'https://simy.one'+route,'inLanguage':lang},ensure_ascii=False)}</script>
<link rel="icon" href="/favicon-32.png"><meta name="theme-color" content="#f6f5f4"><link rel="stylesheet" href="/site-theme.css?v=20261004-theme-1"><link rel="stylesheet" href="/financial-planners.css?v=20261006-4"><script src="/financial-planners.js?v=20261006-1" defer></script></head><body>
<a class="skip" href="#main">{t('本文へ移動','Skip to content')}</a><main id="main" class="fp-shell">
<section class="fp-hero"><div class="fp-frame hero-grid"><div class="hero-copy"><p class="eyebrow">{t("ファイナンシャルプランナーのためのSIMY","SIMY for Financial Planners")}</p><h1>{t('向き合う時間を、<br><em>もっと、お客さまへ。</em>','More time for<br><em>the people<br>you advise.</em>')}</h1><p class="hero-lead">{t('面談の記録を、次の問いと行動へ。<br>準備も、フォローも、声に出す練習も。<br>あなたの相談業務に、SIMYを。','Turn each conversation into questions and next steps.<br>Prepare, follow up and practice out loud.<br>Bring SIMY into your advisory work.')}</p><div class="hero-actions"><a class="button button-primary" href="{download}">{t('SIMYをダウンロード','Download SIMY')} ↗</a><a class="text-link" href="#experience">{t('4つの体験を見る','Explore the experience')} ↓</a></div><p class="hero-platform">{t('Webで整理。iOSアプリでロールプレイ。','Organize on the web. Rehearse in the iOS app.')}</p></div>{hero}</div></section>
<nav class="journey-nav" aria-label="{t('ページ内の体験','On this page')}">'''+''.join(f'<a href="#{ident}"><span>0{i+1}</span>{t(*label)}<b aria-hidden="true">↗</b></a>' for i,(ident,label) in enumerate(zip(['meeting','red-flags','roleplay','knowledge'],steps)))+f'''</nav>
<div id="experience"><section class="fp-story" id="meeting"><div class="fp-frame"><div class="story-top"><span class="story-number">01</span><div><p class="eyebrow">{t('面談の後に','AFTER THE MEETING')}</p><h2>{t('面談が終わる。<br>次の準備が、始まっている。','The meeting ends.<br>The next steps take shape.')}</h2></div></div><div class="story-intro"><p>{t('録音・議事録・保険証券やPDFから、意向と確認事項を整理。次回のアジェンダ、入力候補、フォロー文面まで、一続きで下書きします。','Organize preferences and open questions from recordings, meeting notes and policy documents. Bring the next agenda, proposed entries and follow-up message into one set of drafts.')}</p><div class="request"><small>{t('たとえば、こんな依頼','TRY A REQUEST LIKE THIS')}</small><p>{t('「今日の面談を整理して。次に聞くことと、お礼のメールも用意して」','“Organize today’s meeting. Draft the next questions and a thank-you email.”')}</p></div></div>{desktop}<p class="visual-caption">{sample} {t('内容を確認・修正し、保存や送信を判断します。','Review and edit the content before deciding what to save or send.')}</p></div></section>
{risk_section(lang)}
<section class="fp-story roleplay-story" id="roleplay"><div class="fp-frame"><div class="story-top"><span class="story-number">03</span><div><p class="eyebrow">{t('面談の前に / iOSロールプレイ','BEFORE THE MEETING / iOS VOICE ROLE-PLAY')}</p><h2>{t('その問いを、<br>本番の前に話してみる。','Find the right words.<br>Before the real conversation.')}</h2></div></div><div class="roleplay-grid"><div class="roleplay-copy"><p class="story-description">{t('iOSアプリで、AIをお客さま役に音声ロールプレイ。話す順番、聞き返し方、伝え方を、声に出して練習できます。','Use the iOS app to role-play out loud with AI as your client. Practice the order of your questions, how you follow up and how you explain.')}</p><div class="roleplay-benefit"><span>01</span><div><h3>{t('会う相手をイメージする','Set the scene')}</h3><p>{t('見つけた赤信号をもとに、聞きたい問いを決める。','Use the warning signs to choose the questions you want to practice.')}</p></div></div><div class="roleplay-benefit"><span>02</span><div><h3>{t('反応を聞いて、問いを重ねる','Listen, then ask')}</h3><p>{t('一方的な説明にならない、会話の練習。','Practice a conversation with room for the client’s response.')}</p></div></div><div class="roleplay-benefit"><span>03</span><div><h3>{t('気づきを、次の面談へ','Take the learning forward')}</h3><p>{t('よかった問いと、深掘りしたいことを振り返る。','Reflect on useful questions and what to explore next.')}</p></div></div><a class="app-store-link" href="https://apps.apple.com/app/id6745385262"><img src="/assets/store-badges/app-store.svg" alt="{t('App Storeからダウンロード','Download on the App Store')}" width="150" height="50"></a></div><div class="phone-demo" data-demo="roleplay">{tabs([('場面を選ぶ','Scenario'),('声で練習','Conversation'),('振り返る','Reflection')])}<div class="phone-stage">{phone}<span class="phone-platform">{t("SIMY for iOS","SIMY for iOS")}</span></div><p class="visual-caption">{t('iOS画面の再現イメージ。切り替えて会話例を確認できます。<br>このページでは録音・音声送信は行いません。','Illustrative iOS screens. Switch views to explore the example.<br>This page does not record or transmit audio.')}</p></div></div></div></section>
<section class="fp-story" id="knowledge"><div class="fp-frame"><div class="story-top"><span class="story-number">04</span><div><p class="eyebrow">{t('チームの経験から','LEARN FROM THE TEAM')}</p><h2>{t('先輩の「なぜ」を、<br>明日の自分の問いに。','A colleague’s experience.<br>Your next good question.')}</h2></div></div><div class="story-intro"><p>{t('似たお客さまのケースから、質問の順番や、見落としやすいポイントを面談前に確認。経験を次の相談へつなぎ、チームで学びを積み重ねます。','Before the meeting, draw on similar cases to consider which questions to ask and what you might overlook. Bring experience into the next consultation and keep learning as a team.')}</p><div class="request"><small>{t('たとえば、こんな依頼','TRY A REQUEST LIKE THIS')}</small><p>{t('「明日の面談に似た事例から、最初に聞くことと注意点を教えて」','“Find a similar case for tomorrow’s meeting. What should I ask first, and what should I watch for?”')}</p></div></div>{knowledge}<p class="visual-caption">{sample} {t('社内共有は、顧客情報を除き、承認された内容を対象に。','Team sharing uses approved content with client information removed.')}</p></div></section></div>
<section class="fp-close" id="start"><div class="fp-frame"><p class="eyebrow">{t("次の面談へ","YOUR NEXT CONVERSATION")}</p><div class="closing-grid"><div><h2>{t('次のお客さまに、<br>もう一歩、寄り添える。','Be more present.<br>For your next client.')}</h2><p>{t('まずは一つの面談の整理、または一回のロールプレイから。','Start with one meeting summary or one practice conversation.')}</p></div><div class="closing-actions"><a class="button button-primary" href="{download}">{t('SIMYをダウンロード','Download SIMY')} ↗</a><a class="text-link" href="{home}#pricing">{t('料金・プランを見る','View plans and pricing')} →</a></div></div><details class="availability"><summary>{t('ご利用前に確認したいこと','Before you get started')}<span aria-hidden="true">＋</span></summary><div><p>{t('画面は機能の利用場面を説明するための再現イメージです。実際の表示や利用できる機能は、バージョン・プラン・組織設定により異なります。','These illustrative screens explain how the features may be used. Actual screens and available features vary by version, plan and organization settings.')}</p><p>{t('面談の録音や資料の取り扱いは、お客さまの同意と所属先のルールに沿って行ってください。入力内容、提案、外部への連絡は、担当者が根拠を確認したうえで判断します。','Handle recordings and documents with client consent and in line with your organization’s rules. The responsible advisor checks sources and decides on entries, recommendations and external communications.')}</p></div></details></div></section></main><footer class="fp-shell"><div class="fp-frame fp-footer"><a href="{home}">SIMY <span>{t('ホームへ','Home')} ↗</span></a><p>© 2026 SIMY</p></div></footer></body></html>'''

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for lang in LOCALES:
        path = ROOT / 'site' / (locale_route(lang).lstrip('/') + 'index.html')
        output = apply_header(render(lang)+'\n', path)
        if args.check:
            if not path.exists() or path.read_text() != output:
                raise SystemExit(f'Stale FP page: {path}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(output)
    print('FP pages ' + ('verified' if args.check else 'generated'))

if __name__ == '__main__': main()
