#!/usr/bin/env python3
"""Build static engineering pages from engineering-copy.json; --check rejects stale output."""
from site_header import apply as apply_header
from engineering_experience import hero, experience, CONTENT
import argparse
import json
from html import escape as e
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COPY = json.loads((ROOT / 'scripts/engineering-copy.json').read_text())

def render(c, lang):
    prefix = '/guides/' if lang == 'ja' else f'/guides/{lang.lower()}/'
    related = ''
    for slug,label in c['guides']:
        guide = f'{prefix}{slug}.html'
        if not (ROOT/'site'/guide.lstrip('/')).exists():
            guide = f'/guides/en/{slug}.html'
            label += c['guideLanguageSuffix']
        related += f'<a href="{guide}">{e(label)}<span aria-hidden="true">↗</span></a>'
    headline = ''.join(f'<span>{e(line)}</span>' for line in c['headline'])
    schema = json.dumps({"@context": "https://schema.org", "@type": "WebPage", "name": c['title'], "description": c['description'], "url": 'https://simy.one/' + c['path'], "inLanguage": lang, "isPartOf": {"@type": "WebSite", "name": "SIMY", "url": "https://simy.one/"}}, ensure_ascii=False).replace('<', '\\u003c')
    alternates = '\n'.join(f'  <link rel="alternate" hreflang="{code}" href="https://simy.one/{item["path"]}">' for code,item in COPY.items())
    return f'''<!doctype html>
<!-- Generated by scripts/build-engineering-pages.py; edit scripts/engineering-copy.json. -->
<html lang="{lang}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{e(c['title'])}</title>
  <meta name="description" content="{e(c['description'])}">
  <link rel="canonical" href="https://simy.one/{c['path']}">
{alternates}
  <link rel="alternate" hreflang="x-default" href="https://simy.one/for/en/engineers/">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{e(c['title'])}">
  <meta property="og:description" content="{e(c['description'])}">
  <meta property="og:url" content="https://simy.one/{c['path']}">
  <meta property="og:image" content="https://simy.one/assets/engineer-experience/social-{lang}.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="{e(c['title'])} — {e(c.get("socialAlt", "二重送信の修正前・修正後の説明例" if lang == "ja" else "Illustrative before-and-after submission behavior"))}">
  <meta name="robots" content="index, follow">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{e(c['title'])}">
  <meta name="twitter:description" content="{e(c['description'])}">
  <meta name="twitter:image" content="https://simy.one/assets/engineer-experience/social-{lang}.png">
  <script type="application/ld+json">{schema}</script>
  <meta name="theme-color" content="#f6f5f4">
  <link rel="icon" href="/favicon-32.png" type="image/png">
  <link rel="stylesheet" href="/site-theme.css?v=20261004-theme-1">
  <link rel="stylesheet" href="/engineers.css?v=20261004-theme-1">
  <link rel="stylesheet" href="/engineers-experience.css?v=20261006-locales-1">
  <script src="/engineers-experience.js?v=20261006-4" defer></script>
</head>
<body>
<a class="skip" href="#main">{c['skip']}</a>
<header class="header">
  <div class="site-shell"><div class="frame header-inner">
    <a class="brand" href="{c['home']}" aria-label="SIMY"><img src="/favicon.png" width="32" height="32" alt=""><b>SIMY</b></a>
    <nav aria-label="{'ナビゲーション' if lang == 'ja' else 'Navigation'}"><a href="#delivery">{c['nav']}</a><a href="#start">{c['start']}</a></nav>
    <div class="header-actions"><a class="language" href="/{c['other']}" lang="{'en' if lang == 'ja' else 'ja'}">{c['otherlabel']}</a><a class="button button-dark button-small header-download" href="{c['download']}">{"ダウンロード" if lang == "ja" else "Download"} <span aria-hidden="true">↗</span></a></div>
  </div></div>
</header>
<main id="main" class="site-shell">
  <section class="hero">
    <div class="frame">
      <div class="hero-layout"><div class="hero-copy">
        <p class="eyebrow">{c['eyebrow']}</p>
        <h1>{headline}</h1>
        <p class="hero-lead">{c['lead']}<br>{c['sublead']}</p>
        <div class="hero-actions"><a class="button button-primary primary" href="{c['download']}">{c['install']}<span aria-hidden="true">↗</span></a><a class="secondary" href="#experience">{c['secondary']}<span aria-hidden="true">↓</span></a></div>
        <p class="provider">{c['provider']}</p>
      </div>
      {hero(lang)}</div>
    </div>
  </section>
  {experience(lang)}
  <section class="engineer-close" id="start" aria-labelledby="start-title"><div class="frame">
    <div class="closing-invitation"><div><h2 id="start-title">{e(c['ctaTitle'])}</h2><p>{e(c['startBody'])}</p></div>
      <div class="closing-actions"><a class="button button-primary primary" href="{c['download']}">{e(c['install'])}<span aria-hidden="true">↗</span></a><a class="closing-pricing" href="{c['home']}#pricing">{e(c['pricing'])}<span aria-hidden="true">→</span></a></div>
    </div>
    <nav class="closing-guides" aria-label="{e(c['guidesLabel'])}">{related}</nav>
    <details class="closing-details" id="before-start"><summary>{e(c['beforeStart'])}<span class="toggle" aria-hidden="true">+</span></summary><div class="closing-notes"><p><strong>{e(c['controlLabel'])}</strong>{e(c['controlAnswer'])}</p><p><strong>{e(c['previewLabel'])}</strong>{e(CONTENT[lang]['availabilityBody'])}</p><p>{e(c['availability'])}</p></div></details>
  </div></section>
</main>
<footer class="site-shell"><div class="frame footer"><a class="brand" href="{c['home']}"><b>SIMY</b><span>{c['back']} ↗</span></a><p>{c['footerNote']}</p><span>© 2026 SIMY</span></div></footer>

</body>
</html>'''

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    for lang,c in COPY.items():
        path = ROOT/'site'/c['path']/'index.html'
        output = apply_header(render(c,lang)+'\n', path)
        if args.check:
            if not path.exists() or path.read_text() != output:
                raise SystemExit(f'Stale engineering page: {path.name}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(output)
    for lang, legacy in [('ja', 'engineers.html'), ('en', 'engineers-en.html')]:
        url = '/' + COPY[lang]['path']
        label = 'エンジニア向けページを見る' if lang == 'ja' else 'View SIMY for engineers'
        alias = f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="robots" content="noindex, follow"><meta name="viewport" content="width=device-width, initial-scale=1"><title>SIMY — {label}</title><link rel="canonical" href="https://simy.one{url}"><meta http-equiv="refresh" content="0; url={url}"></head><body><a href="{url}">{label}</a></body></html>
'''
        path = ROOT/'site'/legacy
        if args.check:
            if not path.exists() or path.read_text() != alias:
                raise SystemExit(f'Stale engineering alias: {legacy}')
        else:
            path.write_text(alias)
    print('Engineering pages verified.'  if args.check else 'Engineering pages generated.')
