#!/usr/bin/env python3
"""Build the declared JA/EN occupation and workflow pages; --check is read-only."""
import argparse
import importlib.util
import json
from html import escape as esc
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'scripts/content-pages.json').read_text())
PAGES = {p['id']: p for p in DATA['pages']}
CSS = (ROOT / 'site/content-pages.css').read_text()
spec = importlib.util.spec_from_file_location('guide_intent', ROOT / 'scripts/organize-guide-intent.py')
intent = importlib.util.module_from_spec(spec)
spec.loader.exec_module(intent)
BASE = 'https://simy.one'
LABELS = {
    'ja': {'home': '/ja.html', 'guides': '/guides/index.html', 'hub': '/for/', 'download': '/download.html',
           'nav': '職業別', 'guide': 'ガイド', 'skip': '本文へ移動', 'toc': 'このページの内容',
           'related': '次に読む', 'example': '依頼文の例', 'read': '詳しく読む', 'sources': '参照情報',
           'next': '次は、あなたの仕事で試す。', 'start': 'SIMYをダウンロード', 'pricing': '料金を確認する',
           'availability': '利用できる機能はバージョン、プラン、組織設定によって異なります。まずは自分で確認できる小さな仕事から始めてください。',
           'updated': '更新', 'back': 'SIMYホーム'},
    'en': {'home': '/', 'guides': '/guides/en/index.html', 'hub': '/for/en/', 'download': '/download/en.html',
           'nav': 'For your work', 'guide': 'Guides', 'skip': 'Skip to content', 'toc': 'On this page',
           'related': 'Keep exploring', 'example': 'Example request', 'read': 'Read more', 'sources': 'Sources',
           'next': 'Try it with your next task.', 'start': 'Download SIMY', 'pricing': 'Check pricing',
           'availability': 'Availability depends on version, plan and organization settings. Start with a small task whose result you can inspect yourself.',
           'updated': 'Updated', 'back': 'SIMY home'}
}


def ref(ident, lang):
    if ident == 'engineers':
        return ('/for/engineers/' if lang == 'ja' else '/for/en/engineers/',
                'エンジニア向けSIMY' if lang == 'ja' else 'SIMY for engineers',
                '開発・検証・修正と品質確認を進める。' if lang == 'ja' else 'Move through implementation, verification, repair and quality checks.')
    p = PAGES[ident]
    return p['paths'][lang], p[lang]['title'].removesuffix(' | SIMY'), p[lang]['lead']


def cards(ids, lang):
    result = []
    for ident in ids:
        url, title, description = ref(ident, lang)
        result.append(f'<a class="card" href="{url}"><b>{esc(title)}</b><span>{esc(description)}</span><span class="go">{LABELS[lang]["read"]} →</span></a>')
    return '<div class="cards">' + ''.join(result) + '</div>'


def section(s, lang):
    def paragraphs(key):
        return ''.join(f'<p>{esc(p)}</p>' for p in s.get(key, []))
    body = paragraphs('p')
    if s.get('list'):
        body += '<ul>' + ''.join(f'<li>{esc(t)}</li>' for t in s['list']) + '</ul>'
    if s.get('code'):
        body += f'<pre><code>{esc(s["code"])}</code></pre>'
    if s.get('example'):
        body += f'<div class="example"><p>{esc(s["example"])}</p></div><p class="caption">{LABELS[lang]["example"]}</p>'
    body += paragraphs('pAfter')
    if s.get('links'):
        body += '<ul>' + ''.join(f'<li><a href="{esc(url, quote=True)}">{esc(label)}</a></li>' for url, label in s['links']) + '</ul>'
    if s.get('cards'):
        body += cards(s['cards'], lang)
    return f'<section class="sec" id="{s["id"]}"><h2>{esc(s["title"])}</h2>{body}</section>'


def render(p, lang):
    c, labels = p[lang], LABELS[lang]
    title = c['title'].removesuffix(' | SIMY')
    headline = c.get('headline', title)
    url = BASE + p['paths'][lang]
    is_guide = p['kind'] == 'guide'
    schema = {'@context': 'https://schema.org', '@graph': [
        {'@type': 'Article' if is_guide else 'CollectionPage' if p['kind'] == 'hub' else 'WebPage',
         'headline': title, 'name': title, 'description': c['description'], 'url': url,
         'inLanguage': lang, 'dateModified': DATA['updated'],
         'publisher': {'@type': 'Organization', 'name': 'SIMY', 'url': BASE + '/'}},
        {'@type': 'BreadcrumbList', 'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': 'SIMY', 'item': BASE + labels['home']},
            {'@type': 'ListItem', 'position': 2, 'name': title, 'item': url}]}]}
    alts = ''.join(f'<link rel="alternate" hreflang="{code}" href="{BASE + path}">\n' for code, path in p['paths'].items())
    alts += f'<link rel="alternate" hreflang="x-default" href="{BASE + p["paths"]["en"]}">'
    sections = list(c['sections']) + [{'id': 'related', 'title': labels['related'], 'cards': p['related']}]
    if p.get('sources'):
        sections.append({'id': 'sources', 'title': labels['sources'], 'links': p['sources']})
    toc = ''.join(f'<li><a href="#{s["id"]}">{esc(s["title"])}</a></li>' for s in sections)
    other = 'en' if lang == 'ja' else 'ja'
    html = f'''<!doctype html>
<!-- Generated by scripts/build-content-pages.py; edit scripts/content-pages.json. -->
<html lang="{lang}"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(c['title'])}</title>
<meta name="description" content="{esc(c['description'], quote=True)}">
<link rel="canonical" href="{url}">
{alts}
<meta name="robots" content="index, follow, max-image-preview:large">
<meta property="og:type" content="{'article' if is_guide else 'website'}">
<meta property="og:url" content="{url}">
<meta property="og:title" content="{esc(c['title'], quote=True)}">
<meta property="og:description" content="{esc(c['description'], quote=True)}">
<meta property="og:image" content="https://simy.one/ogp-home-global-202608-v4.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(c['title'], quote=True)}">
<meta name="twitter:description" content="{esc(c['description'], quote=True)}">
<meta name="twitter:image" content="https://simy.one/ogp-home-global-202608-v4.png">
<meta property="article:modified_time" content="{DATA['updated']}">
<meta name="theme-color" content="#f6f5f4">
<link rel="icon" href="/favicon-32.png" type="image/png">
<style>{CSS}</style>
<script type="application/ld+json">{json.dumps(schema, ensure_ascii=False).replace('<', chr(92) + 'u003c')}</script>
</head><body>
<a class="skip" href="#main">{labels['skip']}</a>
<header class="header"><div class="shell header-inner"><a class="brand" href="{labels['home']}">SIMY</a><nav aria-label="{'ナビゲーション' if lang == 'ja' else 'Navigation'}"><a href="{labels['hub']}">{labels['nav']}</a><a href="{labels['guides']}">{labels['guide']}</a><a href="{p['paths'][other]}" lang="{other}" hreflang="{other}">{'English' if other == 'en' else '日本語'}</a></nav></div></header>
<main class="shell" id="main">
<ol class="crumbs"><li><a href="{labels['home']}">SIMY</a></li><li aria-hidden="true">/</li><li>{labels['guide'] if is_guide else labels['nav']}</li></ol>
<div class="hero"><p class="eyebrow">{'GUIDE' if is_guide else 'SIMY FOR YOUR WORK'}</p><h1>{esc(headline)}</h1><p class="lead">{esc(c['lead'])}</p><p class="byline">SIMY · {labels['updated']} <time datetime="{DATA['updated']}">{DATA['updated']}</time></p></div>
<div class="layout"><nav class="toc" aria-label="{labels['toc']}"><p>{labels['toc']}</p><ol>{toc}</ol></nav><div class="reading">{''.join(section(s, lang) for s in sections)}</div></div>
<aside class="next"><h2>{labels['next']}</h2><p>{labels['availability']}</p><div class="actions"><a class="button" href="{labels['download']}">{labels['start']} ↗</a><a href="{labels['home']}#pricing">{labels['pricing']}</a></div></aside>
</main><footer class="shell footer"><a href="{labels['home']}">{labels['back']}</a><span>© 2026 SIMY</span></footer>
<script src="/analytics.js" defer></script>
</body></html>
'''
    return intent.organize(html, p['id']) if is_guide else html


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    count = 0
    for p in PAGES.values():
        for lang, url in p['paths'].items():
            path = ROOT / 'site' / (url.lstrip('/') + ('index.html' if url.endswith('/') else ''))
            output = render(p, lang)
            if args.check:
                if not path.exists() or path.read_text() != output:
                    raise SystemExit(f'Stale content page: {path.relative_to(ROOT)}')
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(output)
            count += 1
    print(f'{count} content pages ' + ('verified.' if args.check else 'generated.'))


if __name__ == '__main__':
    main()
