"""Localized editorial content and rendering for the engineering manga."""
from html import escape as e
import json
from pathlib import Path

DATA = {
'en': {
'hero':['You handed it to AI.','Still babysitting it?','Another “keep going.” Another completion check. The same mistake again.','Spend less time following up, and more time creating.','SIMY prompts the next step when work stops.','Turn past bugs into future checks.','Explore the comic','See screens and features'],
'intro':['SIMY in a comic','Less chasing updates.<br>More time to build.','After handing development to AI…','Sound familiar?'],
'pains':[['Still unfinished','It stops with errors left.','You ask it to keep going again.'],['It said “done”','You try it. It doesn’t work.','You end up checking everything yourself.'],['You already explained it','The same rule gets broken again.','You repeat the same warning.']],
'sources':['Developer posts behind these examples','Adapted from individual accounts on Reddit and other forums. These are paraphrases, not direct quotes or SIMY testimonials.','Stops before errors are fixed','Reports broken code as working','Repeats violations of stated constraints','English · new tab'],
'bridge':'Prompt the next step. Verify the behavior. Prevent repeat mistakes.<br><strong>Follow one bug to see how SIMY helps reduce that work.</strong>',
'panels':[['A bug report','The team learns that a registration was recorded twice just before release.'],['Stop before production','Failed registrations are increasing. The team decides to investigate before release.'],['Work with SIMY','“SIMY! Find the cause, fix it, and test it!” “First, I’ll reproduce it.”'],['Find the cause','A network error triggers duplicate retries: the same request is sent twice.'],['Make a user-focused decision','“An error clears the input. Keep it?” “Yes! Don’t waste the user’s time.”'],['Go beyond the fix','Fix, retest, and review with another AI. The team checks the test and review results.'],['Decide from evidence','Check changes, tests, reviews, user experience, and monitoring before deciding to deploy.'],['Carry the lesson forward','After deployment, the team celebrates and carries the lesson into the next development task.']],
'chapters':[['01 / DELIVERY LOOP','From a request to checks and retries.','When tests find a problem, fix it and check again. Reduce repeated “keep going” prompts.'],['02 / YOUR DECISION','You decide what matters.','“Keep the input after an error?” You choose the policy for your users, then delegate the fix and checks.'],['03 / SQM','One failure becomes a future check.','When building the next form, ask: “Could a retry register it twice?” Use the previous incident to catch missed checks.']],
'fine':['Illustrative comic. Screens and features may differ. Publishing follows permissions and approvals.','Read the full artwork (new tab)','Read the comic as text'],
'mechanism':['How SIMY works: an application-form example','What it looks at. How it checks.','Edited illustrations based on the real screen layouts, using the same application-form example as the comic.','Enlarge screen (new tab)','Rule configuration example, not actual detection or test results.'],
'rows':[
['01 / SIMY DESKTOP APP: DELIVERY LOOP','Local team work in one list.','See your own and teammates’ local work in the SIMY desktop app. Select a thread to check its status and remaining work.',['Team activity: who is working on what, with which AI, locally.','Selected thread: duplicate-registration fix followed by repeated-click and retry tests.','Remaining work: confirm test results and request another AI’s review.']],
['02 / SQM (WEB): PREVENTION RULES','Turn “one registration per retry” into a code check.','Check duplicate prevention in the API and regression tests, beyond the form’s button controls.',['Risk: retries or repeated clicks create two registrations.','Requirement: treat the same application as one; accept different applications normally.','Verify identifier-based deduplication, concurrent requests, and no false blocking of different applications.']],
['03 / SQM (WEB): CHECK SCOPE','Beyond the form: API and storage too.','Preventing duplicates requires understanding the path from the form through acceptance and storage.',['Review the proposed scope before applying it to quality checks.','See the relationships among form, API, storage, email, regression tests, and shared types.']]]},
'es': {
'hero':['Se lo encargaste a la IA.','¿Sigues pendiente de ella?','Otro «continúa». Otra comprobación. El mismo error otra vez.','Dedica menos tiempo al seguimiento y más a crear.','SIMY impulsa el siguiente paso cuando el trabajo se detiene.','Convierte fallos anteriores en futuras comprobaciones.','Descubre el cómic','Ver pantallas y funciones'],
'intro':['SIMY en un cómic','Menos perseguir avances.<br>Más tiempo para crear.','Después de encargar el desarrollo a la IA…','¿Te resulta familiar?'],
'pains':[['Aún no ha terminado','Se detiene con errores pendientes.','Vuelves a pedirle que continúe.'],['Dijo «terminado»','Lo pruebas y no funciona.','Acabas comprobándolo todo tú.'],['Ya lo habías explicado','Vuelve a incumplir la misma regla.','Repites la misma advertencia.']],
'sources':['Publicaciones de desarrolladores','Adaptado de experiencias individuales en Reddit y otros foros. Son paráfrasis, no citas textuales ni testimonios de usuarios de SIMY.','Se detiene antes de resolver los errores','Afirma que un código defectuoso funciona','Vuelve a incumplir restricciones explícitas','Inglés · nueva pestaña'],
'bridge':'Impulsar el siguiente paso. Comprobar el funcionamiento. Evitar repetir errores.<br><strong>Sigue un fallo para ver cómo SIMY ayuda a reducir ese trabajo.</strong>',
'panels':[['Un informe de fallo','Poco antes del lanzamiento, el equipo descubre un registro duplicado.'],['Detenerlo antes de producción','Aumentan los registros fallidos. El equipo decide investigar antes del lanzamiento.'],['Trabajar con SIMY','«¡SIMY! ¡Busca la causa, corrígela y haz las pruebas!» «Primero lo reproduciré».'],['Encontrar la causa','Tras un error de red, los reintentos duplicados envían la misma solicitud dos veces.'],['Decidir pensando en el usuario','«El error borra los datos. ¿Los conservamos?» «¡Sí! No desperdiciemos el tiempo del usuario».'],['Más allá de la corrección','Corregir, volver a probar y revisar con otra IA. El equipo comprueba los resultados.'],['Decidir con evidencias','Revisar cambios, pruebas, revisiones, experiencia de usuario y supervisión antes de desplegar.'],['Aplicar lo aprendido','Tras el despliegue, el equipo celebra y aplica lo aprendido al siguiente desarrollo.']],
'chapters':[['01 / DELIVERY LOOP','Del encargo a las comprobaciones y los reintentos.','Si las pruebas detectan un problema, se corrige y se comprueba de nuevo. Reduce las peticiones de «continúa».'],['02 / TU DECISIÓN','Tú decides lo importante.','«¿Conservamos los datos tras un error?» Tú eliges la política para tus usuarios y delegas la corrección y las comprobaciones.'],['03 / SQM','Un fallo se convierte en una futura comprobación.','Al crear otro formulario: «¿Un reintento podría duplicar el registro?» El incidente anterior ayuda a detectar comprobaciones omitidas.']],
'fine':['Cómic ilustrativo. Las pantallas y funciones pueden variar. La publicación depende de permisos y aprobaciones.','Ver la ilustración completa (nueva pestaña)','Leer el cómic como texto'],
'mechanism':['Cómo funciona SIMY: un formulario de solicitud','Qué observa y cómo lo comprueba.','Ilustraciones editadas a partir de las pantallas reales, con el mismo formulario de solicitud del cómic.','Ampliar pantalla (nueva pestaña)','Ejemplo de configuración de reglas, no resultados reales de detección ni de pruebas.'],
'rows':[
['01 / APLICACIÓN DE ESCRITORIO SIMY: DELIVERY LOOP','El trabajo local del equipo, en una lista.','Consulta tu trabajo local y el de tus compañeros en la aplicación de escritorio SIMY. Selecciona un hilo para ver su estado y lo que queda por hacer.',['Actividad del equipo: quién hace qué, con qué IA, en local.','Hilo seleccionado: corrección de duplicados seguida de pruebas de clics repetidos y reintentos.','Pendiente: confirmar las pruebas y solicitar la revisión de otra IA.']],
['02 / SQM (WEB): REGLAS DE PREVENCIÓN','Convertir «un registro por reintento» en una comprobación.','Comprueba la prevención de duplicados en la API y las pruebas de regresión, además de los botones del formulario.',['Riesgo: los reintentos o clics repetidos crean dos registros.','Condición: tratar la misma solicitud como una y aceptar las diferentes con normalidad.','Comprobar la deduplicación por identificador, las solicitudes simultáneas y que no se bloqueen solicitudes distintas.']],
['03 / SQM (WEB): ALCANCE','Además del formulario: API y almacenamiento.','Evitar duplicados exige conocer el recorrido desde el formulario hasta la recepción y el almacenamiento.',['Revisar el alcance propuesto antes de aplicarlo a las comprobaciones.','Ver las relaciones entre formulario, API, almacenamiento, correo, pruebas y tipos compartidos.']]]},
'fr': {
'hero':['Vous avez confié le travail à l’IA.','Toujours à la surveiller ?','Encore « continue ». Encore une vérification. Encore la même erreur.','Moins de suivi, plus de temps pour créer.','SIMY relance la suite lorsque le travail s’arrête.','Transformez les bugs passés en vérifications futures.','Découvrir la BD','Voir les écrans et les fonctions'],
'intro':['SIMY en bande dessinée','Moins de suivi.<br>Plus de temps pour créer.','Après avoir confié le développement à l’IA…','Cela vous arrive aussi ?'],
'pains':[['Ce n’est pas fini','Elle s’arrête avec des erreurs restantes.','Vous lui demandez encore de continuer.'],['Elle a dit « terminé »','Vous essayez. Ça ne fonctionne pas.','Vous finissez par tout revérifier.'],['Vous l’aviez déjà expliqué','La même règle est encore enfreinte.','Vous répétez le même avertissement.']],
'sources':['Témoignages de développeurs consultés','Adapté de récits individuels sur Reddit et d’autres forums. Il s’agit de reformulations, pas de citations ni de témoignages d’utilisateurs de SIMY.','Arrêt avant la résolution des erreurs','Code défectueux annoncé comme fonctionnel','Violations répétées de contraintes explicites','Anglais · nouvel onglet'],
'bridge':'Relancer la suite. Vérifier le fonctionnement. Éviter les mêmes erreurs.<br><strong>Suivez un bug pour voir comment SIMY aide à réduire ce travail.</strong>',
'panels':[['Un bug signalé','Juste avant la mise en production, l’équipe découvre une inscription en double.'],['Agir avant la production','Les échecs d’inscription augmentent. L’équipe décide d’enquêter avant la sortie.'],['Travailler avec SIMY','« SIMY ! Trouve la cause, corrige et teste ! » « Je vais d’abord reproduire le problème. »'],['Trouver la cause','Après une erreur réseau, des tentatives répétées envoient deux fois la même requête.'],['Décider pour l’utilisateur','« L’erreur efface les champs. Les conserver ? » « Oui ! Respectons le temps de l’utilisateur. »'],['Au-delà de la correction','Correction, nouveaux tests et revue par une autre IA. L’équipe examine les résultats.'],['Décider sur des preuves','Vérifier modifications, tests, revues, expérience utilisateur et surveillance avant le déploiement.'],['Réutiliser la leçon','Après le déploiement, l’équipe célèbre et applique la leçon au développement suivant.']],
'chapters':[['01 / DELIVERY LOOP','De la demande aux vérifications et aux reprises.','Si un test révèle un problème, le corriger puis vérifier à nouveau. Réduisez les demandes répétées de continuer.'],['02 / VOTRE DÉCISION','Vous décidez de l’essentiel.','« Conserver les champs après une erreur ? » Vous choisissez la règle pour vos utilisateurs, puis déléguez correction et vérification.'],['03 / SQM','Un échec devient une vérification future.','Au prochain formulaire : « Une nouvelle tentative pourrait-elle créer un doublon ? » Le bug précédent aide à repérer les vérifications manquantes.']],
'fine':['BD illustrative. Les écrans et fonctions peuvent différer. La publication reste soumise aux droits et approbations.','Voir l’illustration complète (nouvel onglet)','Lire la BD en texte'],
'mechanism':['Comment fonctionne SIMY : un formulaire de demande','Ce qu’il observe et comment il vérifie.','Illustrations modifiées à partir des écrans réels, avec le même exemple de formulaire que dans la BD.','Agrandir l’écran (nouvel onglet)','Exemple de configuration de règle, pas de résultats réels de détection ou de tests.'],
'rows':[
['01 / APPLICATION DE BUREAU SIMY : DELIVERY LOOP','Le travail local de l’équipe dans une liste.','Dans l’application de bureau SIMY, consultez votre travail local et celui de vos collègues. Sélectionnez un fil pour voir son état et les tâches restantes.',['Activité de l’équipe : qui fait quoi, avec quelle IA, en local.','Fil sélectionné : correction du doublon puis tests de clics répétés et de nouvelles tentatives.','À faire : confirmer les tests et demander une revue par une autre IA.']],
['02 / SQM (WEB) : RÈGLES DE PRÉVENTION','Faire de « une inscription par nouvelle tentative » un contrôle.','Vérifiez la prévention des doublons dans l’API et les tests de régression, au-delà des boutons du formulaire.',['Risque : les nouvelles tentatives ou clics répétés créent deux inscriptions.','Condition : une même demande compte une fois ; les demandes différentes sont acceptées.','Vérifier la déduplication par identifiant, les requêtes simultanées et l’absence de blocage des demandes différentes.']],
['03 / SQM (WEB) : PÉRIMÈTRE','Au-delà du formulaire : API et stockage.','Prévenir les doublons demande de comprendre le parcours du formulaire à la réception puis au stockage.',['Vérifier le périmètre proposé avant de l’appliquer aux contrôles qualité.','Voir les liens entre formulaire, API, stockage, e-mails, tests et types partagés.']]]},
'hi': {
'hero':['काम AI को सौंपा।','फिर भी नज़र रखनी पड़ती है?','फिर “जारी रखो” कहना। फिर काम पूरा होने की जाँच। फिर वही गलती।','पीछा करने में कम समय, बनाने में ज़्यादा समय लगाएँ।','काम रुकने पर SIMY अगला कदम बढ़ाने को कहता है।','पिछली त्रुटियों से अगली जाँच तैयार करें।','कॉमिक देखें','स्क्रीन और सुविधाएँ देखें'],
'intro':['कॉमिक में समझें SIMY','बार-बार पूछना कम।<br>बनाने के लिए ज़्यादा समय।','विकास का काम AI को सौंपने के बाद…','क्या आपके साथ भी ऐसा होता है?'],
'pains':[['काम अभी अधूरा है','त्रुटियाँ बाकी हैं, फिर भी काम रुक गया।','आप फिर जारी रखने को कहते हैं।'],['उसने कहा “पूरा हो गया”','चलाकर देखा, तो काम नहीं करता।','आखिर आपको खुद दोबारा जाँचना पड़ता है।'],['आप पहले बता चुके हैं','वही नियम फिर टूट गया।','आप वही चेतावनी दोहराते हैं।']],
'sources':['संदर्भ के लिए डेवलपर की पोस्ट','Reddit और अन्य फ़ोरम पर व्यक्तियों के अनुभवों का रूपांतरण। ये सीधे उद्धरण या SIMY उपयोगकर्ताओं के प्रशंसापत्र नहीं हैं।','त्रुटियाँ दूर होने से पहले काम रुकना','खराब कोड को सही बताना','बताई गई शर्तों का बार-बार उल्लंघन','अंग्रेज़ी · नया टैब'],
'bridge':'अगला कदम बढ़ाना। व्यवहार की जाँच करना। वही गलती दोहराने से बचना।<br><strong>एक त्रुटि के उदाहरण से देखें कि SIMY यह मेहनत कैसे कम करने में मदद करता है।</strong>',
'panels':[['त्रुटि की सूचना','रिलीज़ से ठीक पहले टीम को पता चलता है कि एक पंजीकरण दो बार दर्ज हुआ है।'],['प्रोडक्शन से पहले रोकें','पंजीकरण विफल होने की घटनाएँ बढ़ रही हैं। टीम रिलीज़ से पहले जाँच शुरू करती है।'],['SIMY के साथ काम','“SIMY! कारण खोजो, ठीक करो और टेस्ट करो!” “पहले मैं समस्या दोहराऊँगा।”'],['कारण ढूँढें','नेटवर्क त्रुटि के बाद दोहरे रीट्राई से एक ही अनुरोध दो बार भेजा जाता है।'],['उपयोगकर्ता के हित में फैसला','“त्रुटि पर इनपुट मिट जाता है। रखें?” “हाँ! उपयोगकर्ता का समय बर्बाद न करें।”'],['सिर्फ सुधार नहीं','सुधार, दोबारा टेस्ट और दूसरी AI से समीक्षा। टीम परिणाम जाँचती है।'],['प्रमाण देखकर फैसला','डिप्लॉय से पहले बदलाव, टेस्ट, समीक्षा, उपयोगकर्ता अनुभव और निगरानी जाँचें।'],['सीख आगे ले जाएँ','डिप्लॉय के बाद टीम सफलता मनाती है और अगली बार इस सीख का उपयोग करती है।']],
'chapters':[['01 / DELIVERY LOOP','अनुरोध के बाद जाँच और सुधार तक।','टेस्ट में समस्या मिले तो सुधारें और फिर जाँचें। बार-बार “जारी रखो” कहने की मेहनत कम करें।'],['02 / आपका फैसला','ज़रूरी फैसले आप लें।','“त्रुटि के बाद इनपुट रखें?” उपयोगकर्ता के लिए नीति आप तय करें, सुधार और जाँच सौंप दें।'],['03 / SQM','एक गलती से अगली जाँच तैयार होती है।','अगला फ़ॉर्म बनाते समय पूछें: “क्या रीट्राई से दोहरा पंजीकरण होगा?” पिछली समस्या से छूटी हुई जाँच पहचानें।']],
'fine':['कॉमिक केवल उपयोग का उदाहरण है। स्क्रीन और सुविधाएँ अलग हो सकती हैं। प्रकाशन अनुमतियों और स्वीकृति के अनुसार होता है।','पूरी तस्वीर देखें (नया टैब)','कॉमिक का पाठ पढ़ें'],
'mechanism':['आवेदन फ़ॉर्म से समझें SIMY कैसे काम करता है','क्या देखता है, कैसे जाँचता है।','वास्तविक स्क्रीन की संरचना पर आधारित संपादित उदाहरण। इनमें कॉमिक वाला आवेदन फ़ॉर्म इस्तेमाल किया गया है।','स्क्रीन बड़ी करें (नया टैब)','नियम की सेटिंग का उदाहरण; वास्तविक पहचान या टेस्ट परिणाम नहीं।'],
'rows':[
['01 / SIMY डेस्कटॉप ऐप: DELIVERY LOOP','टीम का स्थानीय काम, एक सूची में।','SIMY डेस्कटॉप ऐप में अपना और साथियों का स्थानीय काम देखें। थ्रेड चुनकर स्थिति और बाकी काम जानें।',['टीम का काम: कौन, किस AI से, स्थानीय तौर पर क्या कर रहा है।','चुना हुआ थ्रेड: दोहरे पंजीकरण का सुधार, फिर बार-बार क्लिक और रीट्राई के टेस्ट।','बाकी काम: टेस्ट परिणाम जाँचें और दूसरी AI से समीक्षा माँगें।']],
['02 / SQM (वेब): रोकथाम के नियम','“रीट्राई पर भी एक पंजीकरण” को कोड की जाँच बनाएँ।','फ़ॉर्म के बटन के साथ API में दोहरे पंजीकरण की रोकथाम और रिग्रेशन टेस्ट भी जाँचें।',['जोखिम: रीट्राई या बार-बार क्लिक से दो पंजीकरण बनते हैं।','शर्त: एक ही आवेदन एक बार दर्ज हो; अलग आवेदन सामान्य रूप से स्वीकार हों।','पहचान कुंजी, एक साथ अनुरोध और अलग आवेदनों को गलती से न रोकने की जाँच करें।']],
['03 / SQM (वेब): जाँच का दायरा','फ़ॉर्म के साथ API और स्टोरेज भी।','दोहराव रोकने के लिए फ़ॉर्म से अनुरोध स्वीकार करने और सहेजने तक के संबंध समझना ज़रूरी है।',['प्रस्तावित दायरा जाँचने के बाद ही गुणवत्ता जाँच में लागू करें।','फ़ॉर्म, API, स्टोरेज, ईमेल, टेस्ट और साझा टाइप के संबंध देखें।']]]},
'zh-Hans': {
'hero':['把工作交给了AI，','还得一直盯着？','又要说“继续”。又要确认是否完成。又犯同样的错。','少花时间催进度，把精力用来创造。','工作停下时，SIMY推动下一步。','把过去的缺陷变成下一次的检查。','通过漫画了解','查看界面与功能'],
'intro':['用漫画了解SIMY','少一点追问进度，<br>多一点专注创造。','把开发工作交给AI之后……','你也遇到过这些事吗？'],
'pains':[['明明还没做完','错误还在，工作却停了。','你又得说一次“继续”。'],['明明说完成了','实际运行，却不能用。','最后还是自己重新检查。'],['明明已经说过','同样的规则又被违反了。','你又得重复同样的提醒。']],
'sources':['参考的开发者帖子','根据Reddit等论坛中的个人经历改写，并非直接引用或SIMY用户评价。','错误尚未修复就停止工作','把无法运行的代码报告为正常','反复违反已说明的约束','英文·新标签页'],
'bridge':'推动下一步，检查实际行为，避免重复犯错。<br><strong>跟随一个缺陷，看看SIMY如何帮助减少这些负担。</strong>',
'panels':[['收到缺陷报告','发布前，团队发现同一条注册被记录了两次。'],['上线前解决','注册失败的报告也在增加。团队决定上线前展开调查。'],['和SIMY一起行动','“SIMY！查明原因，修复并测试！”“我先复现问题。”'],['找到原因','网络错误后的重试重复执行，同一个请求被发送了两次。'],['为用户作出判断','“出错后输入会消失，要保留吗？”“保留！不要浪费用户的时间。”'],['修复之后继续验证','修复、重新测试、另一AI独立审查。团队确认测试和审查结果。'],['根据依据作决定','部署前确认变更、测试、审查、用户体验与监控。'],['把经验带到下一次','部署后团队庆祝，并把这次经验用于下一次开发。']],
'chapters':[['01 / DELIVERY LOOP','从交办，到检查与再次修复。','测试发现问题，就修复后再检查。减少反复说“继续”的负担。'],['02 / 你的判断','重要的事，由你决定。','“失败后保留输入吗？”你为用户决定方针，把修复与检查交给AI。'],['03 / SQM','一次失败，成为下一次的检查。','下次开发另一个表单时：“重试会不会重复注册？”根据过去的缺陷发现遗漏的检查。']],
'fine':['漫画仅为使用示意，界面和功能可能与实际不同。发布须遵循权限与审批。','查看完整原图（新标签页）','阅读漫画文字版'],
'mechanism':['用申请表单示例了解SIMY的工作方式','看什么，怎么检查。','以实际界面结构为基础，将内容替换为与漫画一致的申请表单示例。这些是经过编辑的说明图。','放大界面（新标签页）','规则配置示例，并非实际检测或测试结果。'],
'rows':[
['01 / SIMY桌面应用：DELIVERY LOOP','团队的本地工作，一张列表看清。','在SIMY桌面应用中查看自己和团队成员的本地工作。选择会话，了解当前状态与剩余工作。',['团队工作：谁在本地使用哪个AI推进什么任务。','选中的会话：完成重复注册修复后，进行连点与重试测试。','剩余工作：确认测试结果，请另一AI进行审查。']],
['02 / SQM（网页）：防止复发规则','把“重试也只登记一次”变成代码检查条件。','除了表单按钮控制，还检查API的防重复处理与回归测试。',['风险：重试或连点导致同一申请登记两次。','条件：同一申请只处理一次，不同申请正常登记。','检查标识键去重、并发请求，以及不会误拦截不同申请。']],
['03 / SQM（网页）：检查范围','不仅是表单，还包括API与存储。','防止重复登记，需要理解从表单到接收、保存之间的关系。',['确认AI提出的范围后，再应用到质量检查。','查看表单、API、存储、邮件、回归测试与共享类型之间的关系。']]]}
}


def render(lang, bounds):
    c = DATA[lang]
    manifest = json.loads((Path(__file__).parent / 'engineering-manga-assets.json').read_text())
    images = manifest[lang]
    def image_info(key):
        a = images[key]
        return a['url'], a['width'], a['height']
    asset, aw, ah = image_info('manga')
    panels = []
    transcript = []
    for i, (bound, (title, desc)) in enumerate(zip(bounds, c['panels']), 1):
        x,y,w,h = bound[:4]
        style = f'aspect-ratio:{w}/{h};--image-width:{1055/w*100:.6f}%;--image-left:{-x/w*100:.6f}%;--image-top:{-y/h*100:.6f}%'
        panels.append(f'<li><p class="manga-panel-label"><span>{i:02}</span>{e(title)}</p><div class="manga-panel" style="{style}"><img src="{asset}" width="{aw}" height="{ah}" alt="{e(desc)}" loading="lazy" decoding="async"></div></li>')
        transcript.append(f'<li><strong>{e(title)}</strong><p>{e(desc)}</p></li>')
    chapters = ''.join(f'<article class="manga-chapter"><header><p class="eyebrow">{e(label)}</p><h3>{e(title)}</h3><p>{e(body)}</p></header><ol class="manga-panels" aria-label="{e(title)}">{"".join(panels[a:b])}</ol></article>' for (label,title,body),(a,b) in zip(c['chapters'],[(0,4),(4,7),(7,8)]))
    pains = ''.join(f'<li><span>{e(label)}</span><strong>{e(title)}</strong><p>{e(body)}</p></li>' for label,title,body in c['pains'])
    source_urls = ['https://www.reddit.com/r/ClaudeAI/comments/1n262js/','https://www.reddit.com/r/ClaudeAI/comments/1ma96ha/','https://community.openai.com/t/why-does-codex-repeat-the-same-mistakes/1383615']
    sources = ''.join(f'<li><a href="{url}" target="_blank" rel="noopener">{e(title)} ({e(c["sources"][5])})</a></li>' for url,title in zip(source_urls,c['sources'][2:5]))
    m = c['mechanism']
    rows = []
    for key,(label,title,body,notes) in zip(['delivery','rules','systems'],c['rows']):
        url,width,height = image_info(key)
        points = ''.join(f'<li><strong>{i}</strong><p>{e(text)}</p></li>' for i,text in enumerate(notes,1))
        caveat = f'<p class="mechanism-note">{e(m[4])}</p>' if key == 'rules' else ''
        rows.append(f'<article class="mechanism-row"><div class="mechanism-copy"><p class="eyebrow">{e(label)}</p><h3>{e(title)}</h3><p>{e(body)}</p></div><a class="mechanism-image" href="{url}" target="_blank" rel="noopener" aria-label="{e(title)} — {e(m[3])}"><img src="{url}" width="{width}" height="{height}" alt="{e(title+" "+body)}" loading="lazy" decoding="async"><span>{e(m[3])} ↗</span></a><ol class="mechanism-points">{points}</ol>{caveat}</article>')
    intro = c['intro']; fine = c['fine']
    return f'''<section class="manga-story" id="manga" aria-labelledby="manga-title"><div class="frame">
<div class="manga-intro"><div><p class="eyebrow">{e(intro[0])}</p><h2 id="manga-title">{intro[1]}</h2></div></div>
<aside class="manga-prologue" aria-labelledby="manga-pain-title"><p class="eyebrow">{e(intro[2])}</p><h3 id="manga-pain-title">{e(intro[3])}</h3><ul class="manga-pains">{pains}</ul><details class="manga-sources"><summary>{e(c['sources'][0])}</summary><p>{e(c['sources'][1])}</p><ul>{sources}</ul></details><p class="manga-bridge">{c['bridge']}</p></aside>
{chapters}<div class="manga-reading-tools"><p>{e(fine[0])}</p><a href="{asset}" target="_blank" rel="noopener">{e(fine[1])} ↗</a></div><details class="manga-transcript"><summary>{e(fine[2])}</summary><ol>{''.join(transcript)}</ol></details>
</div></section><section class="manga-mechanism" id="mechanism" aria-labelledby="mechanism-title"><div class="frame"><header><p class="eyebrow">{e(m[0])}</p><h2 id="mechanism-title">{e(m[1])}</h2><p class="mechanism-note">{e(m[2])}</p></header>{''.join(rows)}</div></section>'''
