"""Single source for visitor navigation. Render at build time; enhance without APIs."""
import json
import re
from html import escape as e
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlencode, urlsplit, urlunsplit, parse_qsl

SITE = Path(__file__).resolve().parents[1] / 'site'
LOCALES = ['en', 'ja', 'hi', 'es', 'fr', 'zh-Hans']
NAMES = dict(zip(LOCALES, ['English', '日本語', 'हिन्दी', 'Español', 'Français', '简体中文']))
KEYS = ['product', 'work', 'pricing', 'guides', 'download', 'overview', 'ai', 'how', 'apps', 'why', 'hub', 'engineers', 'sales', 'cases', 'login', 'signup', 'language', 'menu', 'navigation', 'english', 'home']
COPY = dict(zip(LOCALES, [
 ['Product', 'For your work', 'Pricing', 'Guides', 'Download', 'Explore SIMY', 'AI tools', 'How it works', 'Connected apps', 'Why SIMY', 'All occupations', 'Engineers', 'Sales', 'Use cases', 'Log in', 'Sign up', 'Language', 'Menu', 'Primary navigation', 'in English', 'Home'],
 ['プロダクト', '職業別', '料金', 'ガイド', 'ダウンロード', 'SIMYでできること', 'AIツールとの連携', '仕事が進む仕組み', '連携アプリ', 'SIMYの違い', '職業から探す', 'エンジニア', '営業', '活用例を見る', 'ログイン', '新規登録', '言語', 'メニュー', 'メインナビゲーション', '英語', 'ホーム'],
 ['प्रोडक्ट', 'आपके काम के लिए', 'मूल्य', 'गाइड', 'डाउनलोड', 'SIMY को जानें', 'AI टूल', 'यह कैसे काम करता है', 'जुड़े ऐप', 'SIMY क्यों', 'सभी पेशे', 'इंजीनियर', 'बिक्री', 'उपयोग के उदाहरण', 'लॉग इन', 'साइन अप', 'भाषा', 'मेन्यू', 'मुख्य नेविगेशन', 'अंग्रेज़ी में', 'होम'],
 ['Producto', 'Para tu trabajo', 'Precios', 'Guías', 'Descargar', 'Explorar SIMY', 'Herramientas de IA', 'Cómo funciona', 'Apps conectadas', 'Por qué SIMY', 'Todas las profesiones', 'Ingeniería', 'Ventas', 'Casos de uso', 'Iniciar sesión', 'Registrarse', 'Idioma', 'Menú', 'Navegación principal', 'en inglés', 'Inicio'],
 ['Produit', 'Pour votre travail', 'Tarifs', 'Guides', 'Télécharger', 'Découvrir SIMY', 'Outils IA', 'Comment ça marche', 'Apps connectées', 'Pourquoi SIMY', 'Tous les métiers', 'Ingénierie', 'Ventes', 'Cas d’utilisation', 'Connexion', 'S’inscrire', 'Langue', 'Menu', 'Navigation principale', 'en anglais', 'Accueil'],
 ['产品', '适合您的工作', '价格', '指南', '下载', '了解 SIMY', 'AI 工具', '工作原理', '已连接的应用', '为什么选择 SIMY', '所有职业', '工程师', '销售', '使用案例', '登录', '注册', '语言', '菜单', '主导航', '英语', '首页']
]))
COPY = {lang: dict(zip(KEYS, values)) for lang, values in COPY.items()}
REGIONS = {'en': 'us', 'ja': 'jp', 'hi': 'in', 'es': 'es', 'fr': 'fr'}
ACCOUNT_LINKS = json.loads((Path(__file__).parent / 'header-account-links.json').read_text())
START = '<!-- SIMY shared header: generated by scripts/shared_header.py -->'
END = '<!-- /SIMY shared header -->'
ASSETS = '<link rel="stylesheet" href="/shared-header.css?v=20261004-1">\n<script src="/shared-header.js?v=20261004-1" defer></script>\n'


def has_legacy_i18n(source):
    return bool(re.search(r'<script\b[^>]*src=["\'](?:[^"\']*/)?i18n\.js(?:[?"\'])', source))


def home(lang):
    return '/' if lang == 'en' else f'/{lang}.html'


def exists(url):
    return (SITE / (url.lstrip('/') + ('index.html' if url.endswith('/') else ''))).is_file()


def equivalent(path, lang):
    """Return an actual equivalent, or an explicitly labeled fallback."""
    if path in ['index.html'] + [f'{x}.html' for x in LOCALES[1:]]:
        return home(lang), ''
    code = lang.lower() if lang != 'ja' else ''
    if path.startswith('guides/'):
        target = '/guides/' + (code + '/' if code else '') + Path(path).name
    elif path == 'download.html' or path.startswith('download/'):
        target = '/download.html' if lang == 'ja' else f'/download/{code}.html'
    elif path.startswith('for/'):
        tail = path.removeprefix('for/').removeprefix('en/').removesuffix('index.html')
        target = '/for/' + ('' if lang == 'ja' else 'en/') + tail
        return target, '' if lang in ('en', 'ja') else 'english'
    else:
        # Only pages with the legacy translation consumer support query variants.
        source = (SITE / path).read_text() if (SITE / path).exists() else ''
        if has_legacy_i18n(source):
            return '/' + path + '?' + urlencode({'lang': lang, 'locale': lang}), ''
        current = re.search(r'<html\b[^>]*\blang="([^"]+)"', source)
        if current and current[1] == lang:
            return '/' + path, ''
        return home(lang), 'home'
    if exists(target):
        return target, ''
    english = '/guides/en/' + Path(path).name
    return (english, 'english') if exists(english) else (home(lang), 'home')


def configuration(path, lang):
    labels = COPY[lang].copy()
    prefix = '' if lang == 'ja' else lang.lower() + '/'
    occupation = '/for/' if lang == 'ja' else '/for/en/'
    urls = {k: home(lang) + '#' + section for k, section in {'overview': 'product', 'ai': 'codex-connection', 'how': 'how-it-works', 'apps': 'connected-apps', 'why': 'why-simy', 'cases': 'use-cases', 'pricing': 'pricing'}.items()}
    urls.update(brand=home(lang), hub=occupation, engineers=occupation + 'engineers/', sales=occupation + 'sales/', guides='/guides/' + prefix + 'index.html', download='/download.html' if lang == 'ja' else '/download/' + lang.lower() + '.html')
    query = {'lang': lang, 'locale': lang}
    if lang in REGIONS:
        query['region'] = REGIONS[lang]
    urls.update(login='https://app.simy.one/login?' + urlencode(query), signup='https://app.simy.one/signup?' + urlencode(query))
    for key, original in ACCOUNT_LINKS.get(path, {}).items():
        parts = urlsplit(original)
        params = dict(parse_qsl(parts.query))
        if key == 'login' and not parts.query and parts.path == '/':
            urls[key] = original
            continue
        params.update(query)
        if lang not in REGIONS:
            params.pop('region', None)
        urls[key] = urlunsplit(parts._replace(query=urlencode(params)))
    if lang not in ('ja', 'en'):
        for key in ('hub', 'engineers', 'sales'):
            labels[key] += ' (' + labels['english'] + ')'
    labels['current'] = NAMES[lang]
    for code in LOCALES:
        target, fallback = equivalent(path, code)
        urls['locale-' + code] = target
        labels['locale-' + code] = NAMES[code] + (' — ' + labels[fallback] if fallback else '')
    return {'labels': labels, 'urls': urls}


def render(path, lang, dynamic=False):
    configs = {code: configuration(path, code) for code in LOCALES}
    c = configs[lang]
    def label(key):
        return f'<span data-sh-label="{key}">{e(c["labels"][key])}</span>'
    def link(key, extra=''):
        return f'<a data-sh-link="{key}" href="{e(c["urls"][key], quote=True)}"{extra}>{label(key)}</a>'
    def group(key, children):
        return f'<details class="sh-group"><summary>{label(key)}<span class="sh-chevron" aria-hidden="true">⌄</span></summary><div class="sh-panel">' + ''.join(link(x) for x in children) + '</div></details>'
    def navigation():
        return group('product', ['overview', 'ai', 'how', 'apps', 'why']) + group('work', ['hub', 'engineers', 'sales', 'cases']) + ''.join(link(x) for x in ['pricing', 'guides', 'download'])
    language = f'<details class="sh-language"><summary aria-label="{e(c["labels"]["language"])}: {NAMES[lang]}"><span aria-hidden="true">◎</span>' + label('current') + '<span class="sh-chevron" aria-hidden="true">⌄</span></summary><div class="sh-panel">'
    for code in LOCALES:
        _, fallback = equivalent(path, code)
        actual_lang = 'en' if fallback == 'english' else code
        language += link('locale-' + code, f' lang="{code}" hreflang="{actual_lang}"' + (' aria-current="true"' if code == lang else ''))
    language += '</div></details>'
    config = json.dumps(configs, ensure_ascii=False, separators=(',', ':')).replace('<', '\\u003c') if dynamic else '{}'
    return f'''{START}
<header class="simy-header" data-sh-locale="{lang}" data-sh-rail="{'engineering' if path.startswith('for/') and 'engineers/' in path else 'default'}" data-simy-no-translate>
<div class="sh-row">
<a class="sh-brand" data-sh-link="brand" href="{home(lang)}" aria-label="SIMY"><img src="/favicon.png" width="28" height="28" alt="">SIMY</a>
<div class="sh-desktop" role="navigation" aria-label="{e(c['labels']['navigation'])}">{navigation()}</div>
<div class="sh-actions">{language}{link('login', ' class="sh-login" data-existing-account-login')}{link('signup', ' class="sh-signup" data-new-account-signup')}
<details class="sh-mobile"><summary aria-label="{e(c['labels']['menu'])}"><span aria-hidden="true">☰</span></summary><div class="sh-mobile-panel" role="navigation" aria-label="{e(c['labels']['navigation'])}">{navigation()}{link('login', ' data-existing-account-login')}</div></details>
</div></div>
<script type="application/json" data-sh-config>{config}</script>
</header>
{END}'''


class Boundaries(HTMLParser):
    """Locate only outer site navigation, preserving the original surrounding bytes."""
    def __init__(self, source):
        super().__init__(convert_charrefs=False)
        self.offsets = [0]
        for line in source.splitlines(keepends=True):
            self.offsets.append(self.offsets[-1] + len(line))
        self.start = self.end = None
        self.depth = 0
        self.tag = None
        self.in_body = False
        self.feed(source)
    def source_offset(self):
        line, col = self.getpos()
        return self.offsets[line - 1] + col
    def handle_starttag(self, tag, attrs):
        if tag == 'body':
            self.in_body = True
        if self.end is not None or not self.in_body:
            return
        if self.start is None and tag in ('header', 'nav'):
            self.start, self.tag = self.source_offset(), tag
        if self.start is not None and tag == self.tag:
            self.depth += 1
    def handle_endtag(self, tag):
        if self.start is not None and self.end is None and tag == self.tag:
            self.depth -= 1
            if not self.depth:
                self.end = self.source_offset() + len(tag) + 3


def exclusion(path, source):
    if re.search(r'http-equiv=["\']refresh["\']', source, re.I):
        return 'redirect document; retains destination and fallback link'
    if path == 'google-site-verification-TODO.html':
        return 'empty noindex verification setup utility; no visitor content'
    return None


def apply(source, path):
    if exclusion(path, source):
        return source
    lang = re.search(r'<html\b[^>]*\blang="([^"]+)"', source)[1]
    if lang not in LOCALES:
        raise ValueError(f'Unsupported header locale: {path}: {lang}')
    output = render(path, lang, has_legacy_i18n(source))
    if START in source:
        start, end = source.index(START), source.index(END) + len(END)
    else:
        boundary = Boundaries(source)
        start, end = boundary.start, boundary.end
        if start is None:
            start = end = re.search(r'<body\b[^>]*>', source).end()
            output = '\n' + output + '\n'
        elif end is None:
            raise ValueError(f'Unclosed navigation: {path}')
    source = source[:start] + output + source[end:]
    # Obsolete duplicate legal toolbar; actual legal body links are retained.
    source = re.sub(r'\s*<nav class="legal-mobile-toolbar"[^>]*>.*?</nav>', '', source, flags=re.S)
    # Existing scroll callbacks must tolerate replacement of their old nav.
    source = source.replace("var nav = document.getElementById('staticNav');", "var nav = document.getElementById('staticNav');\n      if (!nav) return;") if "if (!nav) return;" not in source else source
    assets = ASSETS
    inline = path.startswith(('guides/', 'download/')) or path == 'download.html'
    source = re.sub(r'<style data-sh-style>.*?</style>\n?', '', source, flags=re.S)
    source = re.sub(r'<link rel="stylesheet" href="/shared-header.css[^"]*">\n?', '', source)
    source = re.sub(r'<script src="/shared-header.js[^"]*" defer></script>\n?', '', source)
    if inline:
        assets = '<style data-sh-style>' + (SITE / 'shared-header.css').read_text() + '</style>\n' + ASSETS.split('\n')[1] + '\n'
    source = source.replace('</head>', assets + '</head>', 1)
    source = re.sub(r'(src="(?:[^"]*/)?i18n\.js)(?:\?[^"]*)?"', r'\1?v=20261004-shared-header-1"', source)
    return source
